spring:
  application:
    name: ingestor

  datasource:
    url: jdbc:postgresql://localhost:5432/building_permits
    username: app
    password: app
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

app:
  building-permits:
    source-url: "https://daten.statistik.zh.ch/ogd/daten/ressourcen/KTZH_00002982_00006183.csv"
    ingest-cron: "0 */1 * * * *"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
